const { createUser, login, getUserById, getUsers, deleteUser, updateUser } = require("./user_controller")
const router = require("express").Router()
const { checkToken } = require("../../api/auth/token_validitation")
router.post("/", checkToken, createUser)
router.get("/", checkToken, getUsers)
router.get("/:id", checkToken, getUserById)
router.patch("/", checkToken, updateUser)
router.delete("/", checkToken, deleteUser)
router.post("/login", login)
module.exports = router
